name: Build QMK firmware
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'QMK Userspace Build'
    permissions:
      contents: read
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
